name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - run: cd test_t1
      - run: dart test
